<a href="https://colab.research.google.com/github/warisaaom/KKU_Data_Mining/blob/master/Data103.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

เรียกใช้ modu numpy

In [14]:
import numpy as np


###numpy array

สร้าง arryด้วยคำสั่งnuppy

In [15]:
np1 = np.array([[1,3,5],[2,4,6]])
np1

array([[1, 3, 5],
       [2, 4, 6]])

In [16]:
np2 = np.array([[1,2],[3,5],[2,0],[4,5]])
np2

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

ให้แสดงข้อมูลเป็นส่วนกลับ

In [17]:
np2.T


array([[1, 3, 2, 4],
       [2, 5, 0, 5]])

In [18]:
np2[0,:]


array([1, 2])

HW6 สร้าง distance matrix (Euclidean) ของ np2
โดยสร้าง function สำหรับคำนวณ Euclidean Distance
def Euclidean(data1,data2):
#process
return dist

In [19]:
def Manhattan(data1,data2):
  distX = data1[0]-data2[0]
  return distX

In [20]:
Manhattan(np2[0,:],np2[1,:])


-2

import math เพื่อใช้คำสั่งทางคณิตศาสตร์

In [21]:
import math

กำหนดให้ Manhattan มีคำสั่งในการคำนวณดังที่แสดงข้างล่าง


In [22]:
def Manhattan(data1,data2):
  distX = abs(data1[0]-data2[0])
  return distX

ตัวอย่างการคำนวณ โดยกำหนดค่าในตัวแปร np2 ที่อยู่ในrecordที่0 และ1 ของทุกคอลัมน์

In [23]:
Manhattan(np2[0,:],np2[1,:])

2

In [24]:
def Manhattan(data1,data2):
  distX = abs(data1[0]-data2[0])
  distY = abs(data1[1]-data2[1])
  return distX+distY

In [25]:
Manhattan(np2[0,:],np2[1,:])

5

สร้างตัวแปรแบบArray ไว้เก็บข้อมูลแบบ เมตริก 4*4

In [26]:
#ตัวอย่าง
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
#ตัวอย่าง
5*np.ones((4,4))



array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [28]:
#ข้อสอบ
dist_mat = np.zeros((4,4))
dist_mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

ใช้คำสั่งการคำนวณใน Manhattan แล้วเก็บข้อมูลที่ได้ทั้งหมดไว้ในตัวแปร dist_math

In [29]:
for i in range(4):
  for j in range(4):
    dist_mat[i,j] = Manhattan(np2[i,:],np2[j,:])
dist_mat


array([[0., 5., 3., 6.],
       [5., 0., 6., 1.],
       [3., 6., 0., 7.],
       [6., 1., 7., 0.]])

In [30]:
np2.shape


(4, 2)

###Distance of norminal or categorical features

(extra) Phyton data structure (Dictoionary)

In [31]:
d_A = {'a':1,2:3,3:5,'cat':6}

In [32]:
d_A

{2: 3, 3: 5, 'a': 1, 'cat': 6}

In [33]:
d_A['cat']

6

In [34]:
d_A['dog'] = [1,2,3,4,5]

In [35]:
d_A

{2: 3, 3: 5, 'a': 1, 'cat': 6, 'dog': [1, 2, 3, 4, 5]}

In [36]:
import pandas as pd

In [37]:
data_dict = {'color' :['red','red','green'],
             'status':['single','married','single']}
data_dict

{'color': ['red', 'red', 'green'], 'status': ['single', 'married', 'single']}

เก็บข้อมูลในตัวแปร data_pd ในรูปแบบของDataFrame

In [38]:
data_pd = pd.DataFrame.from_dict(data_dict)
data_pd

color   status
0    red   single
1    red  married
2  green   single

###Categorical feature distance method#1


เก็บตัวแปรใน record ที่ 0 ในรูปแบบของlist

In [39]:
list(data_pd.iloc[0,:])

['red', 'single']

In [40]:
def meth1_dist(data1,data2):
    N = 0
    print(f'data1 is {data1} and data2 is {data2}')
    for i in range(len(data1)):
      if data1[i] != data2[i]:
          N = N+1
    return N/len(data1)

In [41]:

meth1_dist(list(data_pd.iloc[0,:]),list(data_pd.iloc[1,:]))

data1 is ['red', 'single'] and data2 is ['red', 'married']


0.5

###HW7 Calculate distance matrix of data_pd using meth1_dist()

สร้างตัวแปรที่มีมิติ 3*3

In [42]:
dist_math2 = np.zeros((3,3))
dist_math2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

วนลูปคำนวนค่าโดยใช้สูตรที่กำหนดไว้ใน meth1_dist

In [43]:
for i in range(3):
    for j in range(3):
        dist_math2[i,j] = meth1_dist(list(data_pd.iloc[i,:]),list(data_pd.iloc[j,:]))
dist_math2

data1 is ['red', 'single'] and data2 is ['red', 'single']
data1 is ['red', 'single'] and data2 is ['red', 'married']
data1 is ['red', 'single'] and data2 is ['green', 'single']
data1 is ['red', 'married'] and data2 is ['red', 'single']
data1 is ['red', 'married'] and data2 is ['red', 'married']
data1 is ['red', 'married'] and data2 is ['green', 'single']
data1 is ['green', 'single'] and data2 is ['red', 'single']
data1 is ['green', 'single'] and data2 is ['red', 'married']
data1 is ['green', 'single'] and data2 is ['green', 'single']


array([[0. , 0.5, 0.5],
       [0.5, 0. , 1. ],
       [0.5, 1. , 0. ]])

###Categorical feature distance method#2

กำหนดให้ค่าที่อยู่ในตารางปรากฎเป็นลำดับตัวเลข

In [44]:
data_pd_binary = pd.get_dummies(data_pd)
data_pd_binary

color_green  color_red  status_married  status_single
0            0          1               0              1
1            0          1               1              0
2            1          0               0              1

กำหนดสูตรโดยใช้ binary_sym_dist จากนั้นวนลูปเพื่อคำนวณค่า

In [45]:
def binary_sym_dist(data1,data2):
    q = 0
    rs = 0
    t = 0
    for i in range(len(data1)):
        if data1[i] == data2[i]:
            if data1[i] == 1:
               q = q + 1
            else:
                t = t + 1
        if data1[i] != data2[i]:
            rs = rs + 1    
    return (rs)/(q+rs+t)

แสดงค่าที่ได้จากการคำนวณ

In [46]:
binary_sym_dist(list(data_pd_binary.iloc[i,:]),list(data_pd_binary.iloc[j,:]))

0.0

###HW8 calculate distance matrix of data_pd_binary using binary_sym_dist()

สร้างตัวแปรเก็บข้อมูลที่มีเมตริกแบบ 3*3

In [47]:
binary_sym_dist1 = np.zeros((3,3))
binary_sym_dist1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

วนลูปเพื่อคำนวณตาามสูตร binary_sym_dist แล้วเก็บค่าใน binary_sym_dist1

In [48]:
for i in range(3):
    for j in range(3):
        binary_sym_dist1[i,j] = binary_sym_dist(list(data_pd_binary.iloc[i,:]),list(data_pd_binary.iloc[j,:]))
binary_sym_dist1

array([[0. , 0.5, 0.5],
       [0.5, 0. , 1. ],
       [0.5, 1. , 0. ]])