<a href="https://colab.research.google.com/github/warisaaom/KKU_Data_Mining/blob/master/Data103.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
np1 = np.array([[1,3,5],[2,4,6]])
np1

array([[1, 3, 5],
       [2, 4, 6]])

In [4]:
np2 = np.array([[1,2],[3,5],[2,0],[4,5]])
np2

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [5]:
np2.T


array([[1, 3, 2, 4],
       [2, 5, 0, 5]])

In [7]:
np2[0,:]


array([1, 2])

HW6 สร้าง distance matrix (Euclidean) ของ np2
โดยสร้าง function สำหรับคำนวณ Euclidean Distance
def Euclidean(data1,data2):
#process
return dist

In [8]:
def Manhattan(data1,data2):
  distX = data1[0]-data2[0]
  return distX

In [9]:
Manhattan(np2[0,:],np2[1,:])


-2

In [10]:
import math

In [11]:
def Manhattan(data1,data2):
  distX = abs(data1[0]-data2[0])
  return distX

In [12]:
Manhattan(np2[0,:],np2[1,:])

2

In [13]:
def Manhattan(data1,data2):
  distX = abs(data1[0]-data2[0])
  distY = abs(data1[1]-data2[1])
  return distX+distY

In [14]:
Manhattan(np2[0,:],np2[1,:])

5

In [15]:
#ตัวอย่าง
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
#ตัวอย่าง
5*np.ones((4,4))



array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [17]:
#ข้อสอบ
dist_mat = np.zeros((4,4))
dist_mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
for i in range(4):
  for j in range(4):
    dist_mat[i,j] = Manhattan(np2[i,:],np2[j,:])
dist_mat


array([[0., 5., 3., 6.],
       [5., 0., 6., 1.],
       [3., 6., 0., 7.],
       [6., 1., 7., 0.]])

In [19]:
np2.shape


(4, 2)