<a href="https://colab.research.google.com/github/warisaaom/KKU_Data_Mining/blob/master/%E0%B8%AA%E0%B8%B3%E0%B9%80%E0%B8%99%E0%B8%B2%E0%B8%82%E0%B8%AD%E0%B8%87_Data103.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np


In [4]:
np1 = np.array([[1,3,5],[2,4,6]])
np1

array([[1, 3, 5],
       [2, 4, 6]])

In [5]:
np2 = np.array([[1,2],[3,5],[2,0],[4,5]])
np2

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [6]:
np2.T


array([[1, 3, 2, 4],
       [2, 5, 0, 5]])

In [7]:
np2[0,:]


array([1, 2])

HW6 สร้าง distance matrix (Euclidean) ของ np2
โดยสร้าง function สำหรับคำนวณ Euclidean Distance
def Euclidean(data1,data2):
#process
return dist

In [8]:
def Manhattan(data1,data2):
  distX = data1[0]-data2[0]
  return distX

In [9]:
def Euclidean(data1,data2):
    distX = pow((data1[0]-data2[0]),2)
    distY = pow((data1[1]-data2[1]),2)
    return math.sqrt(distX+distY)

In [10]:
dist_math1 = np.zeros((4,4))
dist_math1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
for i in range(4):
    for j in range(4):
        dist_math1[i,j] = Euclidean(np2[i,:],np2[j,:])
dist_math1

array([[0.        , 3.60555128, 2.23606798, 4.24264069],
       [3.60555128, 0.        , 5.09901951, 1.        ],
       [2.23606798, 5.09901951, 0.        , 5.38516481],
       [4.24264069, 1.        , 5.38516481, 0.        ]])

In [12]:
import math

In [13]:
Manhattan(np2[0,:],np2[1,:])


-2

In [14]:
import math

In [15]:
def Manhattan(data1,data2):
  distX = abs(data1[0]-data2[0])
  return distX

In [16]:
Manhattan(np2[0,:],np2[1,:])

2

In [17]:
def Manhattan(data1,data2):
  distX = abs(data1[0]-data2[0])
  distY = abs(data1[1]-data2[1])
  return distX+distY

In [18]:
Manhattan(np2[0,:],np2[1,:])

5

In [19]:
#ตัวอย่าง
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
#ตัวอย่าง
5*np.ones((4,4))



array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [21]:
#ข้อสอบ
dist_mat = np.zeros((4,4))
dist_mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
for i in range(4):
  for j in range(4):
    dist_mat[i,j] = Manhattan(np2[i,:],np2[j,:])
dist_mat


array([[0., 5., 3., 6.],
       [5., 0., 6., 1.],
       [3., 6., 0., 7.],
       [6., 1., 7., 0.]])

In [23]:
np2.shape


(4, 2)

#Distance of nominal or creategorical features

####(extra)Python data structure (Dictionary)

In [24]:
d_A = {'a':1,2:3,3:5,'cat':6}

In [25]:
d_A

{2: 3, 3: 5, 'a': 1, 'cat': 6}

In [26]:
d_A['cat']

6

In [27]:
d_A['dog'] = [1,2,3,4,5]

In [28]:
d_A

{2: 3, 3: 5, 'a': 1, 'cat': 6, 'dog': [1, 2, 3, 4, 5]}

In [29]:
del d_A[2]

In [30]:
d_A

{3: 5, 'a': 1, 'cat': 6, 'dog': [1, 2, 3, 4, 5]}

In [31]:
import pandas as pd

In [33]:
data_dict = {'color':['red','red','green'],  #color = {'red','green','blue'}
             'statas':['single','married','single']}  #statas = {'single','married','divore'}
data_dict

{'color': ['red', 'red', 'green'], 'statas': ['single', 'married', 'single']}

In [34]:
data_pd = pd.DataFrame.from_dict(data_dict)
data_pd

color   statas
0    red   single
1    red  married
2  green   single

#Categorical feature distance method#1

In [ ]:
list(data_pd.iloc[0,:])

In [ ]:
list(data_pd.iloc[1,:])

In [ ]:
def meth1_dist(data1,data2):
    N = 0
    print(f'data1 is {data1} and data2 is {data2} ')
    for i in range(len(data1)):
        print(f'feature1 of data1 is {data1[i]} , feature1 of data2 is {data2[i]}')
        if data1[i] ==data2[i]:
            N=N+1
            print(f'{data1[i]} is equal {data2[i]} : updated ({N})')
        else:
             print(f'{data1[i]} is equal {data2[i]}')
    return N/len(data1)

In [ ]:
meth1_dist(list(data_pd.iloc[0,:]),list(data_pd.iloc[1,:]))

#HW7 calculate distance matrix og data_pd using meth1_dist()

####Categorical feature distance method#2

In [ ]:
pd.get_dummies(data_pd)

In [ ]:
def binary_dist(dta1,data2):
  q=0
  rs=0
  t=0
  for i in range(len(data1)):
    if data1[i] == data2[i]:
      if data[i] == 1:
        q=q+1
      else:
        t=t+1
    if data[i] !=data2[i]:
          rs=rs+1

  return (rs)/(q+r+s+t)
  